[package]
name = "candy-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
candy-parser = { path = "../candy-parser" }
candy-typecheck = { path = "../candy-typecheck" }
candy-diagnostics = { path = "../candy-diagnostics" }

[dev-dependencies]
serde_json = "1"
